version: '3.8'
services:
  sportschool-api:
    image: sportschool:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:1337
      - ConnectionStrings__SportSchool=Host=127.0.0.1;Database=sport_school;Username=postgres;Password=123
      - KeycloakConfiguration__Audiences=account
      - KeycloakConfiguration__ClientId=ServerSideClient
      - KeycloakConfiguration__ClientSecret=bME3VEqRNjTSVKjUADjvztNYbdNxZGBO
      - KeycloakConfiguration__BaseUrl=http://localhost:8080
      - KeycloakConfiguration__Realm=SportSchool
      - KeycloakConfiguration__ExternalClientConfiguration__OptionalScopes=
      - KeycloakConfiguration__ExternalClientConfiguration__DefaultScopes=
      - KeycloakConfiguration__ExpirationTimeBySeconds=3600
      - KeycloakScopesConfiguration__SportSchoolScopeName=SportSchool.Scope
    ports:
      - "1337:1337"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "sport_school"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
