version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    environment:
      KC_DB: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak_dev_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: 13371337
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_HTTP_PORT: 8080
      PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
    command:
      - start-dev